CREATE TABLE  `isg3`.`PROYECTO` (
  `OID` varchar(50) NOT NULL,
  `ADMINISTRADOR_OID` varchar(50) NOT NULL,
  `ENFERMEDAD_OID` varchar(50) NOT NULL,
  `NOMBRE` varchar(255) default NULL,
  `FECHA_INICIO` date default NULL,
  `FECHA_FIN` date default NULL,
  PRIMARY KEY  (`OID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1

CREATE TABLE ENFERMEDAD (
OID VARCHAR (50) NOT NULL,
TRATAMIENTO_OID VARCHAR (50) NOT NULL,
NOMBRE_COMUN VARCHAR (255),
NOMBRE_TECNICO VARCHAR (255),
DESCRIPCION VARCHAR (255),
PRIMARY KEY(OID)
);

CREATE TABLE ENFERMEDAD_SINTOMA (
OID VARCHAR (50) NOT NULL,
ENFERMEDAD_OID VARCHAR (50) NOT NULL,
SINTOMA_OID VARCHAR (50) NOT NULL,
PRIMARY KEY(OID)
);
CREATE TABLE HISTORIA(
OID VARCHAR (50) NOT NULL,
ENFERMEDAD_OID VARCHAR (50) NOT NULL,
USUARIO_NORMAL_OID VARCHAR (50) NOT NULL,
HISTORIA VARCHAR (4000),
PRIMARY KEY(OID)
);
CREATE TABLE SINTOMA (
OID VARCHAR (50) NOT NULL,
DESCRIPCION VARCHAR (255),
NOMBRE VARCHAR (255),
GRAVEDAD VARCHAR (50),
PRIMARY KEY(OID)
);
CREATE TABLE FIRMA (
OID VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (255),
APELLIDOS VARCHAR (255),
DNI VARCHAR (20),
PRIMARY KEY(OID)
);
CREATE TABLE USUARIO_NORMAL(
OID VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (255),
APELLIDOS VARCHAR (255),
PASSWORD VARCHAR (255),
NIF VARCHAR (20),
EMAIL VARCHAR (255),
PRIMARY KEY(OID)
);
CREATE TABLE USUARIO_CUALIFICADO(
OID VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (255),
APELLIDOS VARCHAR (255),
PASSWORD VARCHAR (255),
NIF VARCHAR (20),
EMAIL VARCHAR (255),
PRIMARY KEY(OID)
);
CREATE TABLE USUARIO_ADMIN(
OID VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (255),
APELLIDOS VARCHAR (255),
PASSWORD VARCHAR (255),
NIF VARCHAR (20),
EMAIL VARCHAR (255),
PRIMARY KEY(OID)
);
CREATE TABLE ENFERMEDAD_USUARIO_CUALIFICADO(
OID VARCHAR (50) NOT NULL,
ENFERMEDAD_OID VARCHAR (50) NOT NULL,
USUARIO_CUALIFICADO VARCHAR (50) NOT NULL,
PRIMARY KEY(OID)
);
CREATE TABLE PROYECTO_USUARIO_NORMAL(
OID VARCHAR (50) NOT NULL,
PROYECTO_OID VARCHAR (50)  NOT NULL,
USUARIO_NORMAL VARCHAR (50) NOT NULL,
PRIMARY KEY(OID)
);
CREATE TABLE ENFERMEDAD_MEDICAMENTO(
OID VARCHAR (50) NOT NULL,
ENFERMEDAD_OID VARCHAR (50) NOT NULL,
MEDICAMENTO_OID VARCHAR (50) NOT NULL,
PRIMARY KEY(OID)
);
CREATE TABLE DONACION (
OID VARCHAR (50) NOT NULL,
PROYECTO_OID VARCHAR (50) NOT NULL,
CANTIDAD INT,
NOMBRE VARCHAR (255),
APELLIDOS VARCHAR (255),
DNI VARCHAR (20),
PAIS VARCHAR (255),
ES_MIEMBRO BOOL,
PRIMARY KEY(OID)
);
CREATE TABLE MEDICAMENTO(
OID VARCHAR (50) NOT NULL,
DENOMINACION VARCHAR (255) NOT NULL,
POSOLOGIA VARCHAR (2000),
PRIMARY KEY(OID)
);
CREATE TABLE TRATAMIENTO(
OID VARCHAR (50) NOT NULL,
FRECUENCIA VARCHAR (255),
DURACION INT,
PRIMARY KEY(OID)
);
CREATE TABLE CENTRO_DIAGNOSTICO(
OID VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (255),
DIRECCION VARCHAR (255),
MUNICIPIO VARCHAR (255),
PROVINCIA VARCHAR (255),
PAIS VARCHAR (255),
PRIMARY KEY(OID)
);
CREATE TABLE ENFERMEDAD_CENTRO(
OID VARCHAR (50) NOT NULL,
ENFERMEDAD_OID VARCHAR (50) NOT NULL,
CENTRO_DIAGNOSTICO_OID VARCHAR(50) NOT NULL,
PRIMARY KEY(OID)
);








